# Generated by Django 5.2.5 on 2025-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
